---
port: 4443
ssl: true
ssl_key_file: /etc/nginx/ssl/tennismatchmaker.co.key
ssl_cert_file: /etc/nginx/ssl/tennismatchmaker.co.chained.crt
environment: production
rackup: private_pub.ru
daemonize: true